[package]
name = "geoviz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tinyfiledialogs = "3.9.1"
fltk = "^1.3"
fltk-theme = "0.4"
fltk-flex = "0.2.1"
